services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/ext1/pyload_config:/config
      - /media/ext1/downloads:/downloads
    ports:
      - 8000:8000
      - 9666:9666
    restart: unless-stopped
