services:
  caddy:
    image: arm64v8/caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /media/ext1/caddy/data:/data
      - /media/ext1/caddy/config:/config
    network_mode: "host"
