version: "3"
services:
  caddy:
    build:
      context: ./
    container_name: caddy
    restart: unless-stopped
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /media/ntfs-volume-1/caddy/data:/data
      - /media/ntfs-volume-1/caddy/config:/config
    network_mode: "host"
