version: "3"
services:
  caddy:
    image: arm64v8/caddy:2.7.2-alpine
    container_name: caddy
    restart: unless-stopped
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /media/ntfs-volume-1/caddy/data:/data
      - /media/ntfs-volume-1/caddy/config:/config
    network_mode: "host"
