version: "3"
services:
  wegmans_clipper:
    build:
      context: ./
      args:
      - WEGMANS_EMAIL=${WEGMANS_EMAIL:?Missing a wegmans's email account}
      - WEGMANS_PASSWORD=${WEGMANS_PASSWORD:?Missing a wegmans's account password}
      - WEGMANS_CRON_SCHEDULE=${WEGMANS_CRON_SCHEDULE:-0 15 * * 1,5}
      dockerfile: ./Dockerfile
