version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8642:80/tcp
    environment:
      TZ: America/New_York
      WEBPASSWORD: ${PIHOLE_WERBPASSWORD:?Missing web password}
    volumes:
      - ./../../etc-pihole:/etc/pihole
      - ./../../etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
