services:
  mcphub:
    image: samanhappy/mcphub:latest
    ports:
      - "3000:3000"
    volumes:
      - /media/ext1/mcphub/mcp_settings.json:/app/mcp_settings.json
    environment:
      NODE_ENV: production
      PORT: 3000
      BASE_PATH: ""
      REQUEST_TIMEOUT: 60000
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN?Missing Github API token for MCP server}
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
