version: "3"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    mem_limit: 1024M
    mem_reservation: 128M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL:?Missing server URL}
    volumes:
      - /media/ext1/jellyfin_config:/config
      - /media/ext1/series:/data/tvshows
      - /media/ext1/movies:/data/movies
      - /media/ext1/music:/data/music
      - /media/ext1/web-media:/data/web-media
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
