version: "3"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    mem_limit: 1024M
    mem_reservation: 128M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL:?Missing server URL}
    volumes:
      - /media/ntfs-volume-1/jellyfin_config:/config
      - /media/ntfs-volume-1/series:/data/tvshows
      - /media/ntfs-volume-1/movies:/data/movies
      - /media/ntfs-volume-1/music:/data/music
      - /media/ntfs-volume-1/web-media:/data/web-media
      - /dev/shm:/config/data/transcoding-temp/transcodes
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
