version: "3"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:arm64v8-latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/ext1/freshrss_config:/config
    ports:
      - 8112:80
    restart: unless-stopped
