services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: raspi_syncthing
    hostname: raspi_syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/ext1/syncthing_config:/config
      - /media/ext1/Cloud:/Cloud
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
